### PR TITLE
Updated the documentation with Linux/MacOS build instructions

### PR DESCRIPTION
**Pull request by Allsimon**
Hello,

I added some documentation about building on Linux/MacOS. 

>Note: The game currently crash after creating a character with:
```
Exception in thread "LWJGL Application" java.lang.RuntimeException: Actor: TextButton
|  Label: OK
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:132)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:122)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.toggle(Button.java:140)
	at com.riiablo.screen.CreateCharacterScreen$7$1.keyDown(CreateCharacterScreen.java:315)
	at com.badlogic.gdx.InputMultiplexer.keyDown(InputMultiplexer.java:80)
	at com.badlogic.gdx.InputMultiplexer.keyDown(InputMultiplexer.java:80)
	at com.badlogic.gdx.backends.lwjgl.DefaultLwjglInput.processEvents(DefaultLwjglInput.java:341)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:220)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.NullPointerException
	at com.riiablo.screen.panel.InventoryPanel.<init>(InventoryPanel.java:284)
	at com.riiablo.screen.GameScreen.<init>(GameScreen.java:334)
	at com.riiablo.screen.GameScreen.<init>(GameScreen.java:255)
	at com.riiablo.screen.CreateCharacterScreen$5.changed(CreateCharacterScreen.java:191)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 10 more
```

I'm not sure if this is a Linux specific issue (didn't try on Windows yet).

The change on `gradlew` is simply a `chmod +x gradlew`

### CODE REVIEW

**Comment by collinsmith** [comment]
Fantastic, I'll take a look when I get a chance!

`CharStats` instances need to be coupled with `d2s` data, which a new character doesn't have. I dropped support for new characters when this change was made until I decided to properly implement character creation. The project will look for save files within your `$diablo_home$/Save` directory, which you may need to copy saves into manually as on windows saves are located somewhere else in 1.14. I use pluggy, so I have old-style saves. Generating a `CharStats`/`d2s` would not be difficult, just haven't gotten around to it since it's not very useful to test on new characters without stats/skills/items.

**Comment by collinsmith** [comment]
I looked into it a bit more. The specific crash you're seeing is caused by not having an attributes initialized correctly because of a new character. I could work around this issue by providing default values at that specific crash point, but it's asserted that certain stats are set for every character (such as `gold`, `hitpoints`, etc). This will eventually be resolved when new characters have a d2s created which calls `CharStats#softReset` which sets these default values.

**Review by collinsmith — CHANGES_REQUESTED** [review]
`You'll need a JDK 8 in order to build this. JDK >14 doesn't work at the moment.`
->
`You'll need JDK 8 in order to build this. JDK >14 doesn't work at the moment.`

Why didn't JDK14 work? JDK8 is used specifically for android compatibility, so that's what I recommend.

What about the notes about the MacOS MPQ file format? AFAIK, there is no Linux version of the game which means you likely copied the MPQ files over, whereas some people may have a MacOS retail copy of the game which uses the MacOS MPQ file format.

Please don't commit whitespace changes.

Is there a reason why `gradlew` is included?

**Comment by yuripourre** [comment]
@collinsmith the LibGDX LWJGL2 backend is not working with OpenJDK 14. I had to upgrade to LWJGL3 to use it. Maybe that's the case?

**Comment by collinsmith** [comment]
Ahh, I see. I remember upgrading to LWJGL2, we'll probably continue that trend with desktop to support as many features as we can on that platform. Android has been finicky with dependencies though (hence why I wrote an entire logging framework because Log4J2 didn't work), so source compatibility will remain at JDK7.

**Comment by Allsimon** [comment]
>Why didn't JDK14 work? 

For me, it was an issue with your gradle wrapper. It is currently configured to version 4.6 (see https://github.com/collinsmith/riiablo/blob/master/gradle/wrapper/gradle-wrapper.properties) and 4.6 doesn't support [Java >= 11](https://github.com/bladecoder/bladecoder-adventure-engine/issues/39). 

I tried to bump Gradle to 6.6.1 (current latest), but I had build issues with it. I didn't investigate further.

>Is there a reason why gradlew is included?
`gradlew` was already committed in the repo, but it was not marked as executable, so if you tried to `./gradlew build` on Linux/MacOS, it would simply throw a "This file is not executable"

>What about the notes about the MacOS MPQ file format? AFAIK, there is no Linux version of the game which means you likely copied the MPQ files over
Yes I just copied the MPQ files. I didn't know there would be differences in MPQ for MacOS, so I didn't tried yet

>Please don't commit whitespace changes.
My bad 😅 IntelliJ did it for me

**Comment by collinsmith** [comment]
I'm not great with building and build scripts, so I'm always worried I'll mess up my house of cards. It's happened before and completely halts development, so I typically leave it alone unless I absolutely need to change it (hence why the wrapper is 2.5 yrs old). It's definitely an area I need to learn more about or get help from someone who understands it 😄

**Comment by collinsmith** [comment]
Closing due to inactivity.

**Pull request closed without merging**
